### ISSUE TITLE
ERROR: MethodError: no method matching unsafe_copyto!(::Vector{…}, ::Int64, ::SentinelArrays.SentinelVector{…}, ::Int64, ::Int64)

### ISSUE THREAD

**Issue by kafisatz** [JuliaData/SentinelArrays.jl#109] opened 2024-11-01 14:17 UTC
MWE 

```
VERSION 
versioninfo() 
using CSV
using DataFrames 
using Pkg 
Pkg.status()
#fi= raw"c:\temp\test.csv"
fi=download("https://gist.githubusercontent.com/kafisatz/be010c9f3c7d53f7b585630a1b3e0e73/raw/776f73af8e55e47f94f2c18f6824ab076452c2ce/gistfile1.txt")
prev = CSV.read(fi,DataFrame,dateformat="dd.mm.yyyy",copycols=true,stringtype=String,pool=false);
unique!(prev);
unique(prev)
```

my error:
```
julia> unique(prev)
ERROR: MethodError: no method matching unsafe_copyto!(::Vector{Union{…}}, ::Int64, ::SentinelArrays.SentinelVector{Float64, Float64, Missing, Vector{…}}, ::Int64, ::Int64)
The function `unsafe_copyto!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  unsafe_copyto!(::Array, ::Any, ::Array, ::Any, ::Any)
   @ Base array.jl:282
  unsafe_copyto!(::BitArray, ::Integer, ::Union{BitArray, Array}, ::Integer, ::Integer)
   @ Base bitarray.jl:456
  unsafe_copyto!(::Memory{T}, ::Any, ::Memory{T}, ::Any, ::Any) where T
   @ Base genericmemory.jl:128
  ...

Stacktrace:
 [1] getindex(x::SentinelArrays.ChainedVector{Union{Missing, Float64}, SentinelArrays.SentinelVector{Float64, Float64, Missing, Vector{Float64}}}, inds::UnitRange{Int64})
   @ SentinelArrays C:\Users\bernhard.konig\.julia\packages\SentinelArrays\v0rcL\src\chainedvector.jl:202
 [2] _threaded_getindex(selected_rows::UnitRange{Int64}, selected_columns::UnitRange{Int64}, df_columns::Vector{AbstractVector}, idx::DataFrames.Index)
   @ DataFrames C:\Users\bernhard.konig\.julia\packages\DataFrames\kcA9R\src\dataframe\dataframe.jl:574
 [3] getindex
   @ C:\Users\bernhard.konig\.julia\packages\DataFrames\kcA9R\src\dataframe\dataframe.jl:616 [inlined]
 [4] #unique#173
   @ C:\Users\bernhard.konig\.julia\packages\DataFrames\kcA9R\src\abstractdataframe\unique.jl:298 [inlined]
 [5] unique(df::DataFrame)
   @ DataFrames C:\Users\bernhard.konig\.julia\packages\DataFrames\kcA9R\src\abstractdataframe\unique.jl:295
 [6] top-level scope
   @ REPL[11]:1
Some type information was truncated. Use `show(err)` to see complete types.

```

**Comment by bkamins** [comment] 2024-11-01 21:11
Thank you for reporting. This is an issue in SentinelArrays.jl.

CC @quinnj

**Comment by quinnj** [comment] 2024-11-01 21:35
I can't reproduce. Can you share what versions you're on @kafisatz? I don't see any usages of `unsafe_copyto!` in current SentinelArrays version.

**Comment by devmotion** [comment] 2024-11-01 21:46
We hit this issue as well, see my comment in #108 (by the way this issue is a duplicate of #107 I think). We had to run Julia with multiple threads to reproduce the problem.

**Comment by devmotion** [comment] 2024-11-01 22:01
I just checked locally, and

1. I can reproduce the problem by running Julia with multiple threads (used `julia --threads=auto` which gives me 6 threads), installing latest versions of CSV and DataFrames, and copying the script in the first comment to the REPL

2. I confirmed locally that #108 fixes the issue (I followed the same procedure but also installed #108 together with CSV and DataFrames)

**Comment by quinnj** [comment] 2024-11-02 03:53
Thanks @devmotion for confirming; I was confused because indeed I just added the unsafe_copyto! usage, but my local branch got messed up and was unexpectedly behind. Going to look at your PR now.

**Closed** 2024-11-02 03:56 UTC
